'use client';

import { useEffect, useRef, useState } from 'react';

// Struktur data pesan dari Bridge HTML
interface BridgeMessageData {
  action: 'DATA_CHANGED';
    key: string;
      payload: any[];
      }
      
      export default function AdminPage() {
        const iframeRef = useRef<HTMLIFrameElement>(null);
          const [logAktivitas, setLogAktivitas] = useState<string>('Belum ada perubahan data.');
          
            useEffect(() => {
                const handler = (event: MessageEvent<BridgeMessageData>) => {
                      if (!event.data || !event.data.action) return;
                      
                            // Menangkap data yang dikirim dari fungsi setData() di HTML
                                  if (event.data.action === 'DATA_CHANGED') {
                                          const { key, payload } = event.data;
                                                  
                                                          // Membersihkan nama key (dari 'gd_jemaat' menjadi 'JEMAAT')
                                                                  const namaTabel = key.replace('gd_', '').toUpperCase();
                                                                          
                                                                                  setLogAktivitas(`[${new Date().toLocaleTimeString()}] Tabel ${namaTabel} baru saja diperbarui! Total data saat ini: ${payload.length}`);
                                                                                          
                                                                                                  console.log(`Log Data Global Bridge (${namaTabel}):`, payload);
                                                                                                  
                                                                                                          // TIPS KEDEPANNYA: 
                                                                                                                  // Di sini kamu bisa langsung melakukan fetch() ke API Backend nyata Next.js 
                                                                                                                          // untuk menyimpan payload data ini ke database asli (seperti Supabase/PostgreSQL/MySQL)
                                                                                                                                  // contoh: fetch('/api/gereja/sync', { method: 'POST', body: JSON.stringify({ tabel: key, data: payload }) })
                                                                                                                                        }
                                                                                                                                            };
                                                                                                                                            
                                                                                                                                                window.addEventListener('message', handler);
                                                                                                                                                
                                                                                                                                                    return () => {
                                                                                                                                                          window.removeEventListener('message', handler);
                                                                                                                                                              };
                                                                                                                                                                }, []);
                                                                                                                                                                
                                                                                                                                                                  // Fungsi pembantu untuk mengirim perintah DARI Next.js KE DALAM iframe HTML
                                                                                                                                                                    const kirimSinyalKeHTML = (actionName: string, extraParams = {}) => {
                                                                                                                                                                        if (iframeRef.current && iframeRef.current.contentWindow) {
                                                                                                                                                                              iframeRef.current.contentWindow.postMessage({ action: actionName, ...extraParams }, '*');
                                                                                                                                                                                  }
                                                                                                                                                                                    };
                                                                                                                                                                                    
                                                                                                                                                                                      return (
                                                                                                                                                                                          <div style={{ display: 'flex', flexDirection: 'column', height: '100vh', fontFamily: 'sans-serif' }}>
                                                                                                                                                                                                
                                                                                                                                                                                                      {/* HEADER BAR ADMIN (DIBUAT DI NEXT.JS) */}
                                                                                                                                                                                                            <div style={{ background: '#1e3a5f', color: '#fff', padding: '12px 20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', boxShadow: '0 2px 4px rgba(0,0,0,0.1)' }}>
                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                              <h2 style={{ margin: 0, fontSize: '18px' }}>Gereja Digital Admin Wrapper (TSX)</h2>
                                                                                                                                                                                                                                        <small style={{ color: '#a0aec0' }}>{logAktivitas}</small>
                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                {/* Tombol Kontrol Luar untuk mengendalikan halaman di dalam HTML */}
                                                                                                                                                                                                                                                                        <div style={{ display: 'flex', gap: '8px' }}>
                                                                                                                                                                                                                                                                                  <button 
                                                                                                                                                                                                                                                                                              onClick={() => kirimSinyalKeHTML('PINDAH_HALAMAN', { pageTarget: 'dashboard' })}
                                                                                                                                                                                                                                                                                                          style={{ padding: '6px 12px', background: '#2c5282', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                Dashboard
                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                    <button 
                                                                                                                                                                                                                                                                                                                                                                onClick={() => kirimSinyalKeHTML('PINDAH_HALAMAN', { pageTarget: 'keuangan' })}
                                                                                                                                                                                                                                                                                                                                                                            style={{ padding: '6px 12px', background: '#2c5282', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                  Keuangan
                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                      <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => kirimSinyalKeHTML('TRIGGER_REFRESH')}
                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ padding: '6px 12px', background: '#e8c547', color: '#0f1a2e', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Refresh Data HTML
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* IFRAME GEREJA DIGITAL */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <iframe
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ref={iframeRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        src="/admin/dashboard.html"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          width: '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: 'none'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }'